public enum Maps {
    LIMGRAVE,
    WEEPING_PENINSULA,
    LIURNIA_OF_THE_LAKES,
    SIOFRA,
    CAELID,
    ALTUS_PLATEAU,
    MOUNTAINTOPS_OF_THE_GIANTS,
    CONSECRATED_SNOWFIELD,
    CRUMBLING_FARUM_AZULA,
    AINSEL_RIVER,
    LAKE_OF_ROT,
    DEEPROOT_DEPTHS
}
